add upload a contract
Volve-gitore/quickss-backend pull request #15
Opened 2021-05-09 13:49 UTC by BlaiseJavan

#### What does this PR do?

- Type here what your pr will do in short

#### Description of Task to be completed?

- Name all the task completed in reference to the one listed in the Jira description

  - [] Task One

  - [] Task Two

#### How should this be manually tested?

- Clone the project through your terminal(VScode terminal)

      git clone https://github.com/Volve-gitore/quickss-backend.git

- Go to the project and Open the project

       cd quickss-backend && cd .

- Open the feature through its branch

       - git checkout 'branch name'

- Install all the dependencies

       npm i

#### Any background context you want to provide?

- Provide some description/context one should know about your PR

#### What are the relevant Jira story?

- add the link got from Jira

#### Screenshots (if appropriate)

- Add some Image if needed

2021-05-19 07:15 UTC, Emile-Nsengimana requested changes
Check all comments above and also remove all `pdf` files used when testing

2021-05-19 07:15 UTC, Emile-Nsengimana commented on src/controllers/Client.js
> +
remove this

2021-05-19 07:15 UTC, Emile-Nsengimana commented on src/controllers/Client.js
> +        '/home/blaise/Documents/projects/volve/quickss/quickss-backend/uploads/'+fileNamee,
Try to avoid hard-coding the `path` to upload files

2021-05-19 07:15 UTC, Emile-Nsengimana commented on src/controllers/Client.js
> +      const abc = await fs.writeFileSync(
Use meaningful variable name

2021-05-19 07:15 UTC, Emile-Nsengimana commented on src/controllers/Client.js
> +      console.log('error ', error);
remove all console

2021-05-19 07:15 UTC, Emile-Nsengimana commented on src/controllers/Client.js
> +      const fileNamee = Date.now()+""+file.originalname;
It will be better to use `date-clientname-contract` as contract file name format

2021-05-22 23:57 UTC, BlaiseJavan commented on src/controllers/Client.js
> +
done

2021-05-23 00:11 UTC, BlaiseJavan commented on src/controllers/Client.js
> +        '/home/blaise/Documents/projects/volve/quickss/quickss-backend/uploads/'+fileNamee,
all cleared

2021-05-23 07:52 UTC, Emile-Nsengimana approved these changes

2021-05-23 07:52 UTC, merged