refactor authentication and authorization
Volve-gitore/quickss-backend pull request #16
Opened 2021-05-23 01:16 UTC by BlaiseJavan

#### What does this PR do?

- Refactor authentication and authorization

#### Description of Task to be completed?

- Name all the task completed in reference to the one listed in the Jira description

  - [] create roles

  - [] access controller 

#### How should this be manually tested?

- Clone the project through your terminal(VScode terminal)

      git clone https://github.com/Volve-gitore/quickss-backend.git

- Go to the project and Open the project

       cd quickss-backend && cd .

- Open the feature through its branch

       - git checkout 'branch name'

- Install all the dependencies

       npm i

#### Any background context you want to provide?

- Provide some description/context one should know about your PR

#### What are the relevant Jira story?

- N/A

#### Screenshots (if appropriate)

- N/A

2021-06-02 11:55 UTC, Emile-Nsengimana requested changes

2021-06-02 11:55 UTC, Emile-Nsengimana commented on src/controllers/role.js
> +        return res.status(400).send({
status code should be `409` for conflict

2021-06-02 11:55 UTC, Emile-Nsengimana commented on src/controllers/role.js
> +        items: roles,
better to have `roles` instead of `items` for convenience

2021-06-02 11:55 UTC, Emile-Nsengimana commented on src/controllers/type.js
>          return res.status(400).send({
change the status code from `400` to `409` (conflict)

2021-06-02 11:55 UTC, Emile-Nsengimana commented on src/roles.js
> + .updateOwn("hotelResto")
do we still use `hotelResto` or `clients`?

2021-06-02 11:55 UTC, Emile-Nsengimana commented on src/routes/client.js
> +router.get('/', auth.grantAccess('readAny', 'hotelResto'), clientController.getClients);
please make sure that all references of `hotelResto` are replaced with `clients`

2021-06-02 11:55 UTC, Emile-Nsengimana commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/npmlog/-/npmlog-4.1.2.tgz#08a7f2a8bf734604779a9efa4ad5cc717abb954b"
this file can be added on `.gitIgnore`

2021-06-02 11:55 UTC, Emile-Nsengimana commented on src/middlewares/auth.js
> +const jwt = require('jsonwebtoken');
Can we stick to `ES6>` syntax

2021-06-06 16:47 UTC, BlaiseJavan commented on src/roles.js
> + .updateOwn("hotelResto")
this is referring to a hotel and resto as an items not a roles.

2021-06-06 16:51 UTC, BlaiseJavan commented on src/routes/client.js
> +router.get('/', auth.grantAccess('readAny', 'hotelResto'), clientController.getClients);
same here.. we cant have a client as role and as action at the same time.. this hotelResto is it represents client on actions(create, read, update, delete).. but as role we have client.

2021-06-10 06:48 UTC, Emile-Nsengimana approved these changes

2021-06-13 09:30 UTC, merged